//  Copyright (c) 2012-2015 Thomas Heller
//  Copyright (c) 2007-2021 Hartmut Kaiser
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/assert.hpp>
#include <hpx/plugin_factories/parcelport_factory_base.hpp>

#include <vector>

HPX_EXPORT hpx::plugins::parcelport_factory_base *parcelport_tcp_factory_init(
    std::vector<hpx::plugins::parcelport_factory_base *>& factories);

namespace hpx::parcelset
{
    void init_static_parcelport_factories(
        std::vector<plugins::parcelport_factory_base *>& factories)
    {
        parcelport_tcp_factory_init(factories);
    }
}
